/**
 * Autonomous Festival & Occasions Merchandising Knowledge Catalog
 * Focused on Fast-Moving Packaged Food Items, Festive Sweets, Confectionery & FMCG
 * Modeled on modern 10-minute Quick-Commerce grocery delivery and packaged FMCG retail standards.
 * Completely independent of user-uploaded inventory CSVs.
 */

export interface FestiveProduct {
  id: string;
  festivalId: string;
  festivalName: string;
  productName: string;
  subCategory: string;
  occasionTag?: "VALENTINE" | "SHIVRATRI" | "GENERAL";
  significanceTag: string; // e.g. "Vrat Essential", "Packaged Mithai", "Dry Fruit Gift Box", "FMCG Festive Snack"
  culturalSignificance: string; // Why this exact item is culturally mandatory/demanded
  targetAudience: string; // e.g. "Households & Fasting Devotees", "Corporate & Family Gifting", "Quick-Commerce Shoppers"
  demandSurgeLevel: "EXTREME" | "VERY_HIGH" | "HIGH" | "STEADY";
  demandMultiplier: number; // e.g. 4.5x
  complianceTag: "VEG_VRAT_CERTIFIED" | "HOLY_RITUAL" | "FESTIVE_DECOR" | "CONFECTIONERY" | "APPAREL_LIFESTYLE" | "TECH_ELECTRONICS" | "PACKED_FOOD_FMCG";
  wholesaleCost: number; // in INR (₹)
  suggestedMSRP: number; // in INR (₹)
  profitMarginPercent: number; // e.g. 35%
  recommendedUnitsSmall: number; // Corner store / quick-commerce dark store
  recommendedUnitsMedium: number; // Supermarket / departmental store
  recommendedUnitsEnterprise: number; // Large hypermarket / wholesale chain
  procurementLeadDays: number; // Days needed from supplier before event
  orderDeadline: string; // Dynamic or fixed target
  iconType: string;
}

export interface FestivalCulturalBriefing {
  festivalId: string;
  festivalName: string;
  dates: string;
  significanceOverview: string;
  culturalRules: string[];
  keyShoppingTrends: string[];
  merchandisingAdvice: string;
}

export const FESTIVAL_CULTURAL_BRIEFINGS: Record<string, FestivalCulturalBriefing> = {
  FEST_2026_NAVRATRI: {
    festivalId: "FEST_2026_NAVRATRI",
    festivalName: "Navratri & Durga Puja (2026)",
    dates: "October 11 – October 19, 2026",
    significanceOverview:
      "A 9-night celebration honoring Goddess Durga and her nine avatars. Millions observe strict fasting (Vrat) consuming only pure satvik, non-grain packaged foods. Quick-commerce delivery experiences massive demand for vacuum-sealed fasting flours, sabudana, makhana, cow ghee, and packaged satvik snacks.",
    culturalRules: [
      "Strictly Vegetarian & Satvik: NO meat, NO eggs, NO onion, NO garlic under any circumstance.",
      "Vrat Grain Rules: Standard wheat and rice are avoided; only Kuttu (Buckwheat), Singhara, Sabudana, and Samak rice are permitted.",
      "Sendha Namak (Rock Salt) replaces regular table salt in all snacks and meals.",
    ],
    keyShoppingTrends: [
      "Explosive quick-commerce orders for Kuttu Atta, Singhara Atta, Sabudana, and Sendha Namak.",
      "Fast-moving packaged snacks: Roasted Makhana, Farali Chivda, and vacuum-packed Kaju Katli.",
      "Pure Cow Ghee and tender coconut water for fast-breaking energy.",
    ],
    merchandisingAdvice:
      "Maintain high front-shelf visibility for 500g/1kg vacuum packs of Kuttu Atta and Sabudana. Create bundled 'Navratri Vrat Thali Kits' for 10-minute quick-commerce delivery.",
  },

  FEST_2026_DUSSEHRA: {
    festivalId: "FEST_2026_DUSSEHRA",
    festivalName: "Dussehra & Vijayadashami (2026)",
    dates: "October 20 – October 21, 2026",
    significanceOverview:
      "Marks the triumph of good over evil. The day is celebrated with traditional festive morning breakfast (Jalebi-Fafda combo boxes), packaged canned sweets (Gulab Jamun, Rasgulla tins), and family feasting ingredients.",
    culturalRules: [
      "Jalebi-Fafda Tradition: Consumed early morning on Vijayadashami for auspicious beginnings.",
      "Mithai Gifting: Exchanging sealed tins and packs of traditional sweets with family and neighbors.",
    ],
    keyShoppingTrends: [
      "Instant morning surge in packaged Jalebi & Fafda breakfast combo boxes.",
      "High volume canned sweets: Haldiram's Rasgulla and Gulab Jamun 1kg sealed tins.",
      "Packaged namkeens, Cadbury Celebrations gift packs, and premium Basmati rice bags for family biryani/pulao.",
    ],
    merchandisingAdvice:
      "Pre-pack Jalebi-Fafda boxes for early morning delivery. Stock 1kg canned sweets heavily as they offer 6-month shelf life with zero wastage risk.",
  },

  FEST_2026_KARWA_CHAUTH: {
    festivalId: "FEST_2026_KARWA_CHAUTH",
    festivalName: "Karwa Chauth (2026)",
    dates: "October 28, 2026",
    significanceOverview:
      "A sacred ritual where married women observe a dawn-to-moonrise waterless fast. High demand for pre-dawn Sargi packages (premium dry fruit boxes, roasted feni, besan laddus) and romantic chocolate hampers for post-fast gifting.",
    culturalRules: [
      "Sargi Feast: Consumed before sunrise; consists of energy-dense dry fruits, sweets, and feni.",
      "Moonrise Fast-Breaking: Broken with fresh water, tea, and rich traditional sweets.",
    ],
    keyShoppingTrends: [
      "Luxury pre-assembled Sargi dry fruit hampers (almonds, cashews, figs, raisins).",
      "Packaged pure desi ghee roasted Feni / Pheni (200g sealed packs).",
      "Bestselling boxed sweets: Besan Laddu and Ferrero Rocher romance packs.",
    ],
    merchandisingAdvice:
      "Promote Sargi food hampers 4 days prior. Position Ferrero Rocher and Cadbury Silk prominently for husband-to-wife gifting.",
  },

  FEST_2026_DIWALI: {
    festivalId: "FEST_2026_DIWALI",
    festivalName: "Dhanteras & Diwali (Deepavali 2026)",
    dates: "November 6 – November 10, 2026",
    significanceOverview:
      "The Mega Festival of Lights and the single largest packaged food, confectionery, and dry fruit gifting season across quick-commerce and retail channels. Millions of sealed gift hampers, mithai tins, and premium snacks are exchanged across India.",
    culturalRules: [
      "Auspicious Gifting: Exchanging sweets, gourmet dry fruits, and chocolates is mandatory.",
      "Lakshmi Puja Prasad: Pure Desi Ghee sweets, Kaju Katli, and dry fruits are offered to the Goddess.",
    ],
    keyShoppingTrends: [
      "Top-selling luxury dry fruit hampers: Happilo / Nutraj 4-in-1 gift boxes.",
      "Confectionery #1: Cadbury Celebrations Silk boxes and Ferrero Rocher Moments.",
      "Mithai dominance: Haldiram's Kaju Katli (500g vacuum pack) and Soan Papdi gift tins.",
      "Party snacks: 1kg family packs of Bhujia Sev and gourmet cookie tins.",
    ],
    merchandisingAdvice:
      "Diwali represents 45% of annual packaged gifting sales. Ensure stock availability at ₹300, ₹600, ₹1000, and ₹2000 price tiers.",
  },

  FEST_2026_CHHATH: {
    festivalId: "FEST_2026_CHHATH",
    festivalName: "Chhath Puja (2026)",
    dates: "November 15 – November 17, 2026",
    significanceOverview:
      "An ancient Vedic celebration honoring the Sun God Surya. Devotees prepare traditional Prasad (Thekua) using pure Desi Ghee, chemical-free sugarcane jaggery, and stone-ground wheat flour.",
    culturalRules: [
      "Extreme Satvik Purity: Thekua prasad must be cooked strictly in pure Desi Cow Ghee with jaggery.",
      "No adulteration or artificial additives allowed in ritual cooking flours.",
    ],
    keyShoppingTrends: [
      "High volume sales of 1L sealed Cow Ghee tins (Amul, Patanjali).",
      "Chemical-free sugarcane jaggery (Bheli Gur) in 1kg sealed packs.",
      "Premium whole wheat sharbati atta and sendha namak rock salt.",
    ],
    merchandisingAdvice:
      "Stock certified pure desi cow ghee and organic jaggery prominently. High repeat basket sizes during the 3-day puja window.",
  },

  FEST_2026_WEDDING_BFCM: {
    festivalId: "FEST_2026_WEDDING_BFCM",
    festivalName: "Peak Wedding Season & Black Friday (2026)",
    dates: "November 20 – December 15, 2026",
    significanceOverview:
      "Over 3.5 million weddings across India drive massive demand for packaged catering essentials, bulk dry fruit return gift boxes, luxury chocolate trays, and gourmet beverages.",
    culturalRules: [
      "Wedding Welcome & Return Gifting: Guests are presented with packaged dry fruit and confectionery boxes.",
      "High-volume banqueting requires bulk packs of basmati rice, pure ghee, and premium tea/coffee.",
    ],
    keyShoppingTrends: [
      "Bulk dry fruits hampers (10-packs for wedding invitation return gifts).",
      "Ferrero Rocher 24-piece luxury trays and imported gourmet cookies.",
      "Family pack beverages and 5kg premium Basmati rice sacks.",
    ],
    merchandisingAdvice:
      "Offer tiered bulk discounts for corporate and wedding return gift orders (10+ hampers).",
  },

  FEST_2026_CHRISTMAS_NYE: {
    festivalId: "FEST_2026_CHRISTMAS_NYE",
    festivalName: "Christmas & New Year 2027",
    dates: "December 20, 2026 – January 2, 2027",
    significanceOverview:
      "Global festive season celebrating Christmas and New Year's Eve parties. In quick-commerce grocery delivery, orders surge for traditional rich plum cakes, gourmet chocolates, party nacho crisps, and sparkling celebration juices.",
    culturalRules: [
      "Christmas Feast: Sharing traditional rich fruit plum cake and hot cocoa.",
      "Midnight Countdown: Party snacking with crunchy chips, nachos, dips, and sparkling drinks.",
    ],
    keyShoppingTrends: [
      "Elite / Britannia Traditional Rich Fruit & Nut Plum Cakes (800g sealed box).",
      "Ferrero Rocher and Hershey's Kisses festive pouches.",
      "Doritos / Cornitos Fiesta Party Packs with salsa dip jars.",
      "Cold-pressed fruit juices and sparkling celebration drinks.",
    ],
    merchandisingAdvice:
      "Position plum cakes at prime checkout counters from Dec 20. Bundle party snacks with dips and beverages for New Year Eve.",
  },

  FEST_2027_SANKRANTI_REPUBLIC: {
    festivalId: "FEST_2027_SANKRANTI_REPUBLIC",
    festivalName: "Makar Sankranti, Pongal & Republic Day (2027)",
    dates: "January 14 – January 26, 2027",
    significanceOverview:
      "Harvest festival celebrating the sun's northern transit with traditional sesame and jaggery sweets ('Til-gul'), sweet Pongal rice, and crunchy peanut chikkis.",
    culturalRules: [
      "Sesame & Jaggery Purity: 'Til-gul ghya, god god bola' — mandatory exchange of til papdi and chikkis.",
      "Pongal Feast: Prepared using freshly harvested rice, pure jaggery, and cow ghee.",
    ],
    keyShoppingTrends: [
      "Bikaji Traditional Til Papdi & Organic Rewari assorted boxes.",
      "Haldiram's Gur Gajak and Peanut Chikki slabs.",
      "Packaged white sesame seeds (500g) and premium Sona Masoori Pongal rice.",
    ],
    merchandisingAdvice:
      "Stock packaged sesame chikkis and rewari 2 weeks before Sankranti. Quick commerce orders peak on Jan 13-14.",
  },

  FEST_2027_VALENTINES_SHIVRATRI: {
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri (2027)",
    dates: "February 14 – March 6, 2027",
    significanceOverview:
      "Dual festive wave combining high-velocity romance chocolate gifting (Valentine's Week, Feb 7–14) immediately followed by Lord Shiva's sacred fasting vigil (Maha Shivratri, March 6) with packaged thandai, roasted makhana, and vrat foods.",
    culturalRules: [
      "💖 Valentine's Gifting (Feb 7–14): Packaged heart-shaped chocolates, premium praline boxes, and gourmet confectionery.",
      "🔱 Maha Shivratri (March 6): Strict 24-hour satvik fast (NO grains, NO eggs, NO onion/garlic). Cooling Thandai drinks, roasted makhana, and kuttu atta.",
    ],
    keyShoppingTrends: [
      "💖 Valentine's: Ferrero Rocher Heart Box, Cadbury Silk Heart Pop, Hershey's Exotic Dark, and Lindt Pralines.",
      "🔱 Shivratri: Paper Boat Kesaria Thandai cans, Farmley Roasted Salted Makhana, Haldiram's Farali Chivda, and Amul Badam Milk.",
    ],
    merchandisingAdvice:
      "Dual Phase Strategy on Quick-Commerce: Push boxed romance chocolates and snack packs until Feb 14; transition instantly to Kesaria Thandai, Makhana jars, and fasting staples on Feb 15.",
  },

  FEST_2027_HOLI_EID: {
    festivalId: "FEST_2027_HOLI_EID",
    festivalName: "Holi & Ramadan / Eid ul-Fitr (2027)",
    dates: "March 20 – March 31, 2027",
    significanceOverview:
      "Spring festive double celebration: Holi feasting with vacuum-sealed Mawa Gujiya boxes, Kesaria Thandai syrups, and crispy mathri, coinciding with holy Ramadan Iftar dates and Eid Sheer Khurma vermicelli packs.",
    culturalRules: [
      "Holi Hospitality: Serving chilled Thandai and authentic Mawa Gujiya sweets to visiting guests.",
      "Ramadan Fast-Breaking: Mandatory breaking of fast at sunset with soft Medjool dates and sweet Sheer Khurma.",
    ],
    keyShoppingTrends: [
      "Haldiram's / Bikaji Baked Mawa Gujiya vacuum gift boxes (500g).",
      "Paper Boat Kesaria Thandai Drink Syrup (750ml bottle).",
      "Haldiram's Crispy Mathri and Namakpara snack pouches.",
      "Saudi Medjool Dates (1kg luxury gift box) and Bambino roasted laccha seviyan.",
    ],
    merchandisingAdvice:
      "Pre-order Mawa Gujiya boxes and Thandai syrups 3 weeks before Holi. Ensure abundant stock of imported dates throughout Ramadan.",
  },
};

export const INDEPENDENT_FESTIVAL_PRODUCTS: FestiveProduct[] = [
  // =========================================================================
  // 1. NAVRATRI & DURGA PUJA 2026 (Oct 11 - 19) — Packed Fasting & Satvik Foods
  // =========================================================================
  {
    id: "NAV-001",
    festivalId: "FEST_2026_NAVRATRI",
    festivalName: "Navratri & Durga Puja",
    productName: "Fortune Kuttu Ka Atta (Buckwheat Fasting Flour) - 500g Vacuum Pack",
    subCategory: "Vrat & Fasting Staples",
    significanceTag: "Mandatory Vrat Staple",
    culturalSignificance:
      "Primary flour consumed during 9-day Navratri fasts for puris and parathas. Traditional wheat is strictly forbidden.",
    targetAudience: "Fasting Households & Devotees",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.8,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 68,
    suggestedMSRP: 105,
    profitMarginPercent: 35.2,
    recommendedUnitsSmall: 120,
    recommendedUnitsMedium: 500,
    recommendedUnitsEnterprise: 3000,
    procurementLeadDays: 14,
    orderDeadline: "2026-09-27",
    iconType: "Wheat",
  },
  {
    id: "NAV-002",
    festivalId: "FEST_2026_NAVRATRI",
    festivalName: "Navratri & Durga Puja",
    productName: "Classic Royal Sabudana (Tapioca Sago Large Pearls) - 1kg Sealed Pouch",
    subCategory: "Vrat & Fasting Staples",
    significanceTag: "Vrat Energy Breakfast",
    culturalSignificance:
      "Essential for Sabudana Khichdi, Kheer, and Vada; the most consumed fasting breakfast item across India.",
    targetAudience: "All Fasting Households",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.5,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 72,
    suggestedMSRP: 115,
    profitMarginPercent: 37.4,
    recommendedUnitsSmall: 150,
    recommendedUnitsMedium: 600,
    recommendedUnitsEnterprise: 3500,
    procurementLeadDays: 14,
    orderDeadline: "2026-09-27",
    iconType: "Package",
  },
  {
    id: "NAV-003",
    festivalId: "FEST_2026_NAVRATRI",
    festivalName: "Navratri & Durga Puja",
    productName: "Tata Sampann Sendha Namak (Himalayan Pink Rock Salt) - 1kg Pack",
    subCategory: "Vrat & Fasting Staples",
    significanceTag: "Sacred Fasting Salt",
    culturalSignificance:
      "Regular sea salt is culturally prohibited during Navratri. Only pure Sendha Namak is permitted for fasting cooking.",
    targetAudience: "Fasting Households",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.2,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 40,
    suggestedMSRP: 65,
    profitMarginPercent: 38.5,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 400,
    recommendedUnitsEnterprise: 2500,
    procurementLeadDays: 12,
    orderDeadline: "2026-09-29",
    iconType: "Sparkles",
  },
  {
    id: "NAV-004",
    festivalId: "FEST_2026_NAVRATRI",
    festivalName: "Navratri & Durga Puja",
    productName: "Farmley Roasted & Lightly Salted Phool Makhana (Fox Nuts) - 200g Airtight Jar",
    subCategory: "Healthy Fasting Snacks",
    significanceTag: "Crispy Vrat Snack",
    culturalSignificance:
      "Roasted in pure ghee with rock salt, makhana is the favorite low-calorie energy snack for fasts.",
    targetAudience: "Urban Fasting Devotees",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.8,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 165,
    suggestedMSRP: 249,
    profitMarginPercent: 33.7,
    recommendedUnitsSmall: 80,
    recommendedUnitsMedium: 320,
    recommendedUnitsEnterprise: 1800,
    procurementLeadDays: 12,
    orderDeadline: "2026-09-29",
    iconType: "Leaf",
  },
  {
    id: "NAV-005",
    festivalId: "FEST_2026_NAVRATRI",
    festivalName: "Navratri & Durga Puja",
    productName: "Amul Pure Cow Desi Ghee - Traditional Bilona (1 Liter Sealed Tin)",
    subCategory: "Pure Ghee & Dairy",
    significanceTag: "Holy Offering & Cooking",
    culturalSignificance:
      "Used for lighting Akhand Diyas for Goddess Durga and preparing pure satvik prasad and sweets.",
    targetAudience: "Households & Temples",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.5,
    complianceTag: "HOLY_RITUAL",
    wholesaleCost: 560,
    suggestedMSRP: 690,
    profitMarginPercent: 18.8,
    recommendedUnitsSmall: 60,
    recommendedUnitsMedium: 250,
    recommendedUnitsEnterprise: 1500,
    procurementLeadDays: 10,
    orderDeadline: "2026-10-01",
    iconType: "Coffee",
  },
  {
    id: "NAV-006",
    festivalId: "FEST_2026_NAVRATRI",
    festivalName: "Navratri & Durga Puja",
    productName: "Haldiram's Phalahari Farali Chivda & Potato Mixture - 200g Pouch",
    subCategory: "Packaged Snacks & Namkeen",
    significanceTag: "Ready Fasting Snack",
    culturalSignificance:
      "Ready-to-eat spiced potato sticks and peanut mixture certified for consumption during Hindu fasts.",
    targetAudience: "Office & Home Fasting Shoppers",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.9,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 55,
    suggestedMSRP: 85,
    profitMarginPercent: 35.3,
    recommendedUnitsSmall: 120,
    recommendedUnitsMedium: 450,
    recommendedUnitsEnterprise: 2400,
    procurementLeadDays: 10,
    orderDeadline: "2026-10-01",
    iconType: "Package",
  },
  {
    id: "NAV-007",
    festivalId: "FEST_2026_NAVRATRI",
    festivalName: "Navratri & Durga Puja",
    productName: "Haldiram's Pure Kaju Katli (Satvik Silver Foil Sweets) - 400g Vacuum Pack",
    subCategory: "Packaged Sweets & Mithai",
    significanceTag: "Satvik Sweet Offering",
    culturalSignificance:
      "Made with 100% cashews and sugar without grain flours; completely satvik and offered to Goddess Durga.",
    targetAudience: "Households & Puja Visitors",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.4,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 320,
    suggestedMSRP: 450,
    profitMarginPercent: 28.9,
    recommendedUnitsSmall: 50,
    recommendedUnitsMedium: 200,
    recommendedUnitsEnterprise: 1200,
    procurementLeadDays: 8,
    orderDeadline: "2026-10-03",
    iconType: "Cake",
  },
  {
    id: "NAV-008",
    festivalId: "FEST_2026_NAVRATRI",
    festivalName: "Navratri & Durga Puja",
    productName: "Paper Boat 100% Pure Tender Coconut Water - (Pack of 6 x 200ml Tetra Paks)",
    subCategory: "Packaged Beverages",
    significanceTag: "Natural Fasting Hydration",
    culturalSignificance:
      "Preferred natural electrolyte drink consumed during long fasting hours and post-Garba night dances.",
    targetAudience: "Fasting Devotees & Garba Dancers",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.2,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 190,
    suggestedMSRP: 270,
    profitMarginPercent: 29.6,
    recommendedUnitsSmall: 60,
    recommendedUnitsMedium: 240,
    recommendedUnitsEnterprise: 1500,
    procurementLeadDays: 10,
    orderDeadline: "2026-10-01",
    iconType: "Sparkles",
  },

  // =========================================================================
  // 2. DUSSEHRA 2026 (Oct 20 - 21) — Sweets, Breakfast Combos & Feasting FMCG
  // =========================================================================
  {
    id: "DUS-001",
    festivalId: "FEST_2026_DUSSEHRA",
    festivalName: "Dussehra (Vijayadashami)",
    productName: "Bikaji Fresh Jalebi & Fafda Morning Festive Breakfast Combo - 500g Sealed Box",
    subCategory: "Packaged Sweets & Mithai",
    significanceTag: "Vijayadashami Breakfast Tradition",
    culturalSignificance:
      "Eaten on Dussehra morning across Western and Central India to celebrate Lord Rama's victory over Ravana.",
    targetAudience: "Families & Morning Shoppers",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.6,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 140,
    suggestedMSRP: 220,
    profitMarginPercent: 36.4,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 450,
    recommendedUnitsEnterprise: 2200,
    procurementLeadDays: 5,
    orderDeadline: "2026-10-15",
    iconType: "Cake",
  },
  {
    id: "DUS-002",
    festivalId: "FEST_2026_DUSSEHRA",
    festivalName: "Dussehra (Vijayadashami)",
    productName: "Haldiram's Sponge Rasgulla in Light Sugar Syrup - 1kg Sealed Can",
    subCategory: "Packaged Sweets & Mithai",
    significanceTag: "Vijayadashami Sweet Exchange",
    culturalSignificance:
      "Rasgulla tins are the quintessential Vijayadashami celebration sweet across Eastern and Northern India.",
    targetAudience: "Family Gatherings & Corporate Treats",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.8,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 150,
    suggestedMSRP: 225,
    profitMarginPercent: 33.3,
    recommendedUnitsSmall: 80,
    recommendedUnitsMedium: 350,
    recommendedUnitsEnterprise: 1800,
    procurementLeadDays: 10,
    orderDeadline: "2026-10-10",
    iconType: "Package",
  },
  {
    id: "DUS-003",
    festivalId: "FEST_2026_DUSSEHRA",
    festivalName: "Dussehra (Vijayadashami)",
    productName: "Cadbury Celebrations Rich Assorted Chocolate Gift Box - 177g Gift Pack",
    subCategory: "Chocolates & Confectionery",
    significanceTag: "Family Festive Gifting",
    culturalSignificance:
      "Bestselling modern festive gift pack on quick-commerce grocery for Vijayadashami family visits and celebrations.",
    targetAudience: "Youth & Festive Shoppers",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.5,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 110,
    suggestedMSRP: 150,
    profitMarginPercent: 26.7,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 400,
    recommendedUnitsEnterprise: 2500,
    procurementLeadDays: 8,
    orderDeadline: "2026-10-12",
    iconType: "Gift",
  },
  {
    id: "DUS-004",
    festivalId: "FEST_2026_DUSSEHRA",
    festivalName: "Dussehra (Vijayadashami)",
    productName: "Daawat Rozana Gold Basmati Rice - 5kg Festive Feast Bag",
    subCategory: "Packaged Cooking Staples",
    significanceTag: "Grand Family Feast Rice",
    culturalSignificance:
      "Premium aged long-grain basmati rice purchased in bulk for Dussehra family biryanis and festive feasts.",
    targetAudience: "Household Kitchens",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.2,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 380,
    suggestedMSRP: 495,
    profitMarginPercent: 23.2,
    recommendedUnitsSmall: 50,
    recommendedUnitsMedium: 200,
    recommendedUnitsEnterprise: 1200,
    procurementLeadDays: 10,
    orderDeadline: "2026-10-10",
    iconType: "Wheat",
  },

  // =========================================================================
  // 3. KARWA CHAUTH 2026 (Oct 28) — Sargi Hampers & Pre-Dawn Packed Nutrition
  // =========================================================================
  {
    id: "KC-001",
    festivalId: "FEST_2026_KARWA_CHAUTH",
    festivalName: "Karwa Chauth",
    productName: "Happilo Royal Sargi Dry Fruits Luxury Gift Box (Almonds, Cashews, Anjeer & Raisins 800g)",
    subCategory: "Dry Fruits & Nuts Hampers",
    significanceTag: "Pre-Dawn Sargi Nutrition",
    culturalSignificance:
      "Traditional gift from mother-in-law consumed before sunrise to sustain women through 15 hours of waterless fast.",
    targetAudience: "Mothers-in-law & Fasting Women",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.4,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 520,
    suggestedMSRP: 799,
    profitMarginPercent: 34.9,
    recommendedUnitsSmall: 60,
    recommendedUnitsMedium: 250,
    recommendedUnitsEnterprise: 1500,
    procurementLeadDays: 12,
    orderDeadline: "2026-10-16",
    iconType: "Gift",
  },
  {
    id: "KC-002",
    festivalId: "FEST_2026_KARWA_CHAUTH",
    festivalName: "Karwa Chauth",
    productName: "Haldiram's Pure Desi Ghee Roasted Feni / Pheni - 200g Sealed Sargi Pack",
    subCategory: "Vrat & Fasting Staples",
    significanceTag: "Traditional Sargi Dish",
    culturalSignificance:
      "Soaked in warm saffron milk, Feni is the mandatory pre-dawn food item eaten before sunrise on Karwa Chauth.",
    targetAudience: "Fasting Wives & Households",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.1,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 75,
    suggestedMSRP: 120,
    profitMarginPercent: 37.5,
    recommendedUnitsSmall: 90,
    recommendedUnitsMedium: 350,
    recommendedUnitsEnterprise: 2000,
    procurementLeadDays: 10,
    orderDeadline: "2026-10-18",
    iconType: "Cake",
  },
  {
    id: "KC-003",
    festivalId: "FEST_2026_KARWA_CHAUTH",
    festivalName: "Karwa Chauth",
    productName: "Ferrero Rocher Premium Hazelnut Chocolates - 16 Pieces Gold Gift Box",
    subCategory: "Chocolates & Confectionery",
    significanceTag: "Husband-Wife Love Gift",
    culturalSignificance:
      "Popular romantic reward and fast-breaking gift presented by husbands upon viewing the moon.",
    targetAudience: "Couples & Modern Gifting",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.6,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 410,
    suggestedMSRP: 549,
    profitMarginPercent: 25.3,
    recommendedUnitsSmall: 70,
    recommendedUnitsMedium: 300,
    recommendedUnitsEnterprise: 1800,
    procurementLeadDays: 8,
    orderDeadline: "2026-10-20",
    iconType: "Heart",
  },

  // =========================================================================
  // 4. DHANTERAS & DIWALI 2026 (Nov 6 - 10) — The #1 FMCG Gifting Extravaganza
  // =========================================================================
  {
    id: "DIW-001",
    festivalId: "FEST_2026_DIWALI",
    festivalName: "Dhanteras & Diwali (Deepavali)",
    productName: "Happilo Royal 4-in-1 Festive Luxury Dry Fruits Hamper (Almonds, Cashews, Pistas, Raisins 1kg)",
    subCategory: "Dry Fruits & Nuts Hampers",
    significanceTag: "Premier Diwali Gift Box",
    culturalSignificance:
      "India's #1 corporate and family Diwali gift. Signifies prosperity, health, and auspicious blessing of Goddess Lakshmi.",
    targetAudience: "Corporate Buyers & Families",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 5.0,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 680,
    suggestedMSRP: 1099,
    profitMarginPercent: 38.1,
    recommendedUnitsSmall: 150,
    recommendedUnitsMedium: 750,
    recommendedUnitsEnterprise: 5000,
    procurementLeadDays: 20,
    orderDeadline: "2026-10-17",
    iconType: "Gift",
  },
  {
    id: "DIW-002",
    festivalId: "FEST_2026_DIWALI",
    festivalName: "Dhanteras & Diwali (Deepavali)",
    productName: "Cadbury Celebrations Silk Special Selection Chocolate Gift Hamper - 250g Luxury Box",
    subCategory: "Chocolates & Confectionery",
    significanceTag: "Mega Confectionery Gifting",
    culturalSignificance:
      "The undisputed national modern gifting symbol for Diwali celebrations across Indian households.",
    targetAudience: "All Gifting Consumers",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.8,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 240,
    suggestedMSRP: 325,
    profitMarginPercent: 26.2,
    recommendedUnitsSmall: 200,
    recommendedUnitsMedium: 1000,
    recommendedUnitsEnterprise: 7000,
    procurementLeadDays: 15,
    orderDeadline: "2026-10-22",
    iconType: "Gift",
  },
  {
    id: "DIW-003",
    festivalId: "FEST_2026_DIWALI",
    festivalName: "Dhanteras & Diwali (Deepavali)",
    productName: "Haldiram's Kaju Katli Premium Gold Box - 500g Vacuum Pack",
    subCategory: "Packaged Sweets & Mithai",
    significanceTag: "Lakshmi Puja Sweet Prasad",
    culturalSignificance:
      "The quintessential Diwali sweet offered during evening Lakshmi-Ganesha Puja and shared with relatives.",
    targetAudience: "Households & Puja Devotees",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.7,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 390,
    suggestedMSRP: 550,
    profitMarginPercent: 29.1,
    recommendedUnitsSmall: 120,
    recommendedUnitsMedium: 500,
    recommendedUnitsEnterprise: 3500,
    procurementLeadDays: 10,
    orderDeadline: "2026-10-27",
    iconType: "Cake",
  },
  {
    id: "DIW-004",
    festivalId: "FEST_2026_DIWALI",
    festivalName: "Dhanteras & Diwali (Deepavali)",
    productName: "Bikano Royal Festive Combo - Gulab Jamun (500g) + Soan Papdi (500g) Dual Gift Tin",
    subCategory: "Packaged Sweets & Mithai",
    significanceTag: "Bestselling Dual Mithai Pack",
    culturalSignificance:
      "Unbeatable mass-gifting item on quick-commerce grocery; long shelf life and universally accepted sweet pairing.",
    targetAudience: "Mass Market & Corporate Gifting",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.3,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 210,
    suggestedMSRP: 320,
    profitMarginPercent: 34.4,
    recommendedUnitsSmall: 150,
    recommendedUnitsMedium: 600,
    recommendedUnitsEnterprise: 4000,
    procurementLeadDays: 14,
    orderDeadline: "2026-10-23",
    iconType: "Package",
  },
  {
    id: "DIW-005",
    festivalId: "FEST_2026_DIWALI",
    festivalName: "Dhanteras & Diwali (Deepavali)",
    productName: "Ferrero Rocher Moments Festive Gift Pack - 24 Crisp Hazelnut Pralines (144g)",
    subCategory: "Chocolates & Confectionery",
    significanceTag: "Premium Affordable Confectionery",
    culturalSignificance:
      "High-velocity gifting SKU designed specifically for festive seasons with premium gold-foil packaging.",
    targetAudience: "Young Families & Colleagues",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.0,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 195,
    suggestedMSRP: 269,
    profitMarginPercent: 27.5,
    recommendedUnitsSmall: 140,
    recommendedUnitsMedium: 550,
    recommendedUnitsEnterprise: 3500,
    procurementLeadDays: 12,
    orderDeadline: "2026-10-25",
    iconType: "Sparkles",
  },
  {
    id: "DIW-006",
    festivalId: "FEST_2026_DIWALI",
    festivalName: "Dhanteras & Diwali (Deepavali)",
    productName: "Haldiram's Bikaneri Bhujia Sev - 1kg Mega Value Saver Pouch",
    subCategory: "Packaged Snacks & Namkeen",
    significanceTag: "Diwali Host Savory Staple",
    culturalSignificance:
      "Served in every Indian home alongside Diwali sweets to balance the palate for visiting guests and relatives.",
    targetAudience: "Every Indian Home",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.9,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 215,
    suggestedMSRP: 295,
    profitMarginPercent: 27.1,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 450,
    recommendedUnitsEnterprise: 3000,
    procurementLeadDays: 10,
    orderDeadline: "2026-10-27",
    iconType: "Package",
  },
  {
    id: "DIW-007",
    festivalId: "FEST_2026_DIWALI",
    festivalName: "Dhanteras & Diwali (Deepavali)",
    productName: "Britannia Good Day Assorted Gourmet Cookies Festive Tin - 600g Embossed Tin",
    subCategory: "Packaged Bakery & Cookies",
    significanceTag: "Tea-Time Festive Cookies",
    culturalSignificance:
      "Keepsake reusable embossed tin containing cashew, almond, and butter cookies; evergreen festive gift.",
    targetAudience: "Family & Neighbor Gifting",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.4,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 185,
    suggestedMSRP: 275,
    profitMarginPercent: 32.7,
    recommendedUnitsSmall: 80,
    recommendedUnitsMedium: 320,
    recommendedUnitsEnterprise: 2000,
    procurementLeadDays: 12,
    orderDeadline: "2026-10-25",
    iconType: "Cake",
  },

  // =========================================================================
  // 5. CHHATH PUJA 2026 (Nov 15 - 17) — Vedic Satvik Prasad Ingredients
  // =========================================================================
  {
    id: "CHH-001",
    festivalId: "FEST_2026_CHHATH",
    festivalName: "Chhath Puja & Dev Deepavali",
    productName: "Amul Shuddh Cow Desi Ghee - 1 Liter Sealed Tin for Thekua Prasad",
    subCategory: "Pure Ghee & Dairy",
    significanceTag: "Sacred Prasad Pure Ghee",
    culturalSignificance:
      "Chhath prasad (Thekua) can only be cooked in unadulterated pure Cow Ghee to offer to Sun God Surya.",
    targetAudience: "Vrat Devotees & Bihari Households",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.6,
    complianceTag: "HOLY_RITUAL",
    wholesaleCost: 560,
    suggestedMSRP: 690,
    profitMarginPercent: 18.8,
    recommendedUnitsSmall: 80,
    recommendedUnitsMedium: 350,
    recommendedUnitsEnterprise: 2200,
    procurementLeadDays: 10,
    orderDeadline: "2026-11-05",
    iconType: "Coffee",
  },
  {
    id: "CHH-002",
    festivalId: "FEST_2026_CHHATH",
    festivalName: "Chhath Puja & Dev Deepavali",
    productName: "Organic Desi Sugarcane Bheli Jaggery (Gur) - Chemical Free 1kg Sealed Pack",
    subCategory: "Vrat & Fasting Staples",
    significanceTag: "Traditional Natural Sweetener",
    culturalSignificance:
      "Traditional natural sweetener required for boiling Rasiya (kheer) and kneading Thekua dough on Chhath.",
    targetAudience: "Chhath Devotees",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.3,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 65,
    suggestedMSRP: 105,
    profitMarginPercent: 38.1,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 400,
    recommendedUnitsEnterprise: 2500,
    procurementLeadDays: 12,
    orderDeadline: "2026-11-03",
    iconType: "Leaf",
  },
  {
    id: "CHH-003",
    festivalId: "FEST_2026_CHHATH",
    festivalName: "Chhath Puja & Dev Deepavali",
    productName: "Aashirvaad Select 100% MP Sharbati Whole Wheat Atta - 5kg Sealed Bag",
    subCategory: "Packaged Cooking Staples",
    significanceTag: "Coarse Wheat Flour for Thekua",
    culturalSignificance:
      "Premium whole wheat flour used to fry hundreds of crispy Thekua offerings for the evening Arghya ritual.",
    targetAudience: "Chhath Devotee Families",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.8,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 260,
    suggestedMSRP: 335,
    profitMarginPercent: 22.4,
    recommendedUnitsSmall: 60,
    recommendedUnitsMedium: 250,
    recommendedUnitsEnterprise: 1500,
    procurementLeadDays: 8,
    orderDeadline: "2026-11-07",
    iconType: "Wheat",
  },

  // =========================================================================
  // 6. PEAK WEDDING SEASON & BFCM 2026 (Nov 20 - Dec 15) — Catering & Return Gifts
  // =========================================================================
  {
    id: "WED-001",
    festivalId: "FEST_2026_WEDDING_BFCM",
    festivalName: "Peak Wedding Season & Black Friday",
    productName: "Happilo Royal Wedding Return Gift Dry Fruits Hamper - (Pack of 5 x 400g Boxes)",
    subCategory: "Dry Fruits & Nuts Hampers",
    significanceTag: "Invitation & Return Gift Pack",
    culturalSignificance:
      "Pre-packed dry fruit gift boxes distributed alongside wedding cards and given to guests as return gifts.",
    targetAudience: "Wedding Families & Event Planners",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.9,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 1450,
    suggestedMSRP: 2250,
    profitMarginPercent: 35.6,
    recommendedUnitsSmall: 30,
    recommendedUnitsMedium: 120,
    recommendedUnitsEnterprise: 800,
    procurementLeadDays: 15,
    orderDeadline: "2026-11-05",
    iconType: "Gift",
  },
  {
    id: "WED-002",
    festivalId: "FEST_2026_WEDDING_BFCM",
    festivalName: "Peak Wedding Season & Black Friday",
    productName: "Ferrero Rocher Luxury Golden Gift Pyramid - 24 Pieces Gold Pack",
    subCategory: "Chocolates & Confectionery",
    significanceTag: "Wedding Reception Luxury Treat",
    culturalSignificance:
      "Displayed on VIP dessert tables and given to bridal guests during Sangeet and Reception celebrations.",
    targetAudience: "Banquets & Luxury Hosts",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.5,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 620,
    suggestedMSRP: 849,
    profitMarginPercent: 27.0,
    recommendedUnitsSmall: 50,
    recommendedUnitsMedium: 200,
    recommendedUnitsEnterprise: 1200,
    procurementLeadDays: 12,
    orderDeadline: "2026-11-08",
    iconType: "Sparkles",
  },
  {
    id: "WED-003",
    festivalId: "FEST_2026_WEDDING_BFCM",
    festivalName: "Peak Wedding Season & Black Friday",
    productName: "India Gate Classic Super Basmati Rice - 5kg Premium Bag",
    subCategory: "Packaged Cooking Staples",
    significanceTag: "Wedding Banquet Rice",
    culturalSignificance:
      "Extra-long grain basmati rice chosen by wedding caterers and hosts for signature Shaadi Biryanis.",
    targetAudience: "Wedding Caterers & Families",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.3,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 490,
    suggestedMSRP: 625,
    profitMarginPercent: 21.6,
    recommendedUnitsSmall: 40,
    recommendedUnitsMedium: 180,
    recommendedUnitsEnterprise: 1100,
    procurementLeadDays: 10,
    orderDeadline: "2026-11-10",
    iconType: "Wheat",
  },

  // =========================================================================
  // 7. CHRISTMAS & NEW YEAR 2027 (Dec 20 - Jan 2) — Cakes, Chocolates & Party Sips
  // =========================================================================
  {
    id: "XMAS-001",
    festivalId: "FEST_2026_CHRISTMAS_NYE",
    festivalName: "Christmas & New Year 2027",
    productName: "Elite Traditional Rich Fruit & Nut Plum Cake (Rum & Spice Soaked) - 800g Box",
    subCategory: "Packaged Bakery & Cookies",
    significanceTag: "Christmas Centerpiece Cake",
    culturalSignificance:
      "The undisputed classic Christmas food tradition; shared on Christmas Eve and gifted to colleagues.",
    targetAudience: "All Christmas Celebrants",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.8,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 310,
    suggestedMSRP: 475,
    profitMarginPercent: 34.7,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 450,
    recommendedUnitsEnterprise: 2800,
    procurementLeadDays: 14,
    orderDeadline: "2026-12-06",
    iconType: "Cake",
  },
  {
    id: "XMAS-002",
    festivalId: "FEST_2026_CHRISTMAS_NYE",
    festivalName: "Christmas & New Year 2027",
    productName: "Hershey's Kisses Creamy Milk Chocolates - Festive Pouches (Pack of 2 x 150g)",
    subCategory: "Chocolates & Confectionery",
    significanceTag: "Christmas Stocking Treat",
    culturalSignificance:
      "Iconic holiday chocolate drops loved by kids and adults for holiday stockings and Secret Santa gifts.",
    targetAudience: "Secret Santa & Kids",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.9,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 190,
    suggestedMSRP: 270,
    profitMarginPercent: 29.6,
    recommendedUnitsSmall: 90,
    recommendedUnitsMedium: 360,
    recommendedUnitsEnterprise: 2200,
    procurementLeadDays: 10,
    orderDeadline: "2026-12-10",
    iconType: "Heart",
  },
  {
    id: "XMAS-003",
    festivalId: "FEST_2026_CHRISTMAS_NYE",
    festivalName: "Christmas & New Year 2027",
    productName: "Raw Pressery 100% Valencia Cold Pressed Juices - (Pack of 4 x 250ml Bottles)",
    subCategory: "Packaged Beverages",
    significanceTag: "Holiday Brunch Refreshment",
    culturalSignificance:
      "Premium preservative-free cold-pressed juices ordered for holiday brunches and party mixers.",
    targetAudience: "Urban Health Conscious Parties",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.4,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 240,
    suggestedMSRP: 340,
    profitMarginPercent: 29.4,
    recommendedUnitsSmall: 60,
    recommendedUnitsMedium: 240,
    recommendedUnitsEnterprise: 1500,
    procurementLeadDays: 8,
    orderDeadline: "2026-12-12",
    iconType: "Sparkles",
  },
  {
    id: "XMAS-004",
    festivalId: "FEST_2026_CHRISTMAS_NYE",
    festivalName: "Christmas & New Year 2027",
    productName: "Doritos Nacho Cheese Fiesta Party Pack with Salsa Dip - (Pack of 3 x 150g)",
    subCategory: "Packaged Snacks & Namkeen",
    significanceTag: "New Year Eve Party Snack",
    culturalSignificance:
      "Number one crunch snack pack ordered in bulk on quick-commerce platforms for midnight countdown parties.",
    targetAudience: "NYE Party Hosts & Youth",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.2,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 150,
    suggestedMSRP: 225,
    profitMarginPercent: 33.3,
    recommendedUnitsSmall: 110,
    recommendedUnitsMedium: 450,
    recommendedUnitsEnterprise: 2700,
    procurementLeadDays: 8,
    orderDeadline: "2026-12-12",
    iconType: "Package",
  },

  // =========================================================================
  // 8. MAKAR SANKRANTI / PONGAL 2027 (Jan 14 - 26) — Til Sweets, Chikki & Rice
  // =========================================================================
  {
    id: "SNK-001",
    festivalId: "FEST_2027_SANKRANTI_REPUBLIC",
    festivalName: "Makar Sankranti / Pongal & Republic Day",
    productName: "Bikaji Traditional Til Papdi & Organic Rewari Assorted Box - 800g Sealed Pack",
    subCategory: "Packaged Sweets & Mithai",
    significanceTag: "Sankranti Sesame Delicacy",
    culturalSignificance:
      "Thin crispy sesame wafers (Til Papdi) and jaggery rewari consumed to celebrate the sun entering Capricorn.",
    targetAudience: "Every Indian Household",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.6,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 175,
    suggestedMSRP: 260,
    profitMarginPercent: 32.7,
    recommendedUnitsSmall: 120,
    recommendedUnitsMedium: 500,
    recommendedUnitsEnterprise: 3000,
    procurementLeadDays: 14,
    orderDeadline: "2026-12-31",
    iconType: "Sun",
  },
  {
    id: "SNK-002",
    festivalId: "FEST_2027_SANKRANTI_REPUBLIC",
    festivalName: "Makar Sankranti / Pongal & Republic Day",
    productName: "Haldiram's Pure Gur Gajak & Peanut Chikki Bars - 500g Gift Box",
    subCategory: "Packaged Sweets & Mithai",
    significanceTag: "Winter Jaggery Sweet",
    culturalSignificance:
      "Crunchy jaggery and peanut/sesame brittle eaten on rooftops during kite-flying battles.",
    targetAudience: "Kite Revelers & Families",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.1,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 130,
    suggestedMSRP: 195,
    profitMarginPercent: 33.3,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 400,
    recommendedUnitsEnterprise: 2400,
    procurementLeadDays: 12,
    orderDeadline: "2027-01-02",
    iconType: "Package",
  },
  {
    id: "SNK-003",
    festivalId: "FEST_2027_SANKRANTI_REPUBLIC",
    festivalName: "Makar Sankranti / Pongal & Republic Day",
    productName: "India Gate Sona Masoori Classic Rice - 5kg Bag for Pongal & Khichdi",
    subCategory: "Packaged Cooking Staples",
    significanceTag: "Harvest Festival Cooking",
    culturalSignificance:
      "Aromatic harvest rice used to prepare sweet and savory Pongal pots across South India and Khichdi in the North.",
    targetAudience: "South & North Indian Households",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.5,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 320,
    suggestedMSRP: 425,
    profitMarginPercent: 24.7,
    recommendedUnitsSmall: 50,
    recommendedUnitsMedium: 220,
    recommendedUnitsEnterprise: 1300,
    procurementLeadDays: 10,
    orderDeadline: "2027-01-04",
    iconType: "Wheat",
  },

  // =========================================================================
  // 9. VALENTINE'S DAY & MAHA SHIVRATRI 2027 — Dual Romance & Fasting Foods
  // =========================================================================

  // --- VALENTINE'S ROMANCE TREATS (10 FMCG Packed Food SKUs) ---
  {
    id: "VAL-001",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Ferrero Rocher Heart-Shaped Luxury Hazelnut Pralines Box - (16 Pieces Gold Pack)",
    subCategory: "Chocolates & Confectionery",
    occasionTag: "VALENTINE",
    significanceTag: "Signature Romance Gifting",
    culturalSignificance:
      "The #1 bestselling Valentine's Day romance confectionery item in India. Gold-wrapped hazelnut balls in a heart keepsake box.",
    targetAudience: "Young Couples & Romantic Partners",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 5.0,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 450,
    suggestedMSRP: 649,
    profitMarginPercent: 30.7,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 400,
    recommendedUnitsEnterprise: 2500,
    procurementLeadDays: 14,
    orderDeadline: "2027-01-31",
    iconType: "Heart",
  },
  {
    id: "VAL-002",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Cadbury Dairy Milk Silk Heart Pop Chocolate Bar - 150g Special Edition",
    subCategory: "Chocolates & Confectionery",
    occasionTag: "VALENTINE",
    significanceTag: "Bestselling Youth Valentine Treat",
    culturalSignificance:
      "Viral youth romantic snack featuring a pop-out chocolate heart center. Massive quick-commerce impulse buy.",
    targetAudience: "Youth & College Couples",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.8,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 125,
    suggestedMSRP: 175,
    profitMarginPercent: 28.6,
    recommendedUnitsSmall: 180,
    recommendedUnitsMedium: 750,
    recommendedUnitsEnterprise: 4500,
    procurementLeadDays: 10,
    orderDeadline: "2027-02-04",
    iconType: "Heart",
  },
  {
    id: "VAL-003",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Hershey's Exotic Dark Raspberry & Goji Gourmet Chocolates - (Pack of 2 x 100g Bars)",
    subCategory: "Chocolates & Confectionery",
    occasionTag: "VALENTINE",
    significanceTag: "Artisanal Dark Chocolate",
    culturalSignificance:
      "Premium whole blueberries and raspberries dipped in luscious dark chocolate; trending high-end Valentine gift.",
    targetAudience: "Gourmet Confectionery Lovers",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.2,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 195,
    suggestedMSRP: 290,
    profitMarginPercent: 32.8,
    recommendedUnitsSmall: 80,
    recommendedUnitsMedium: 320,
    recommendedUnitsEnterprise: 1800,
    procurementLeadDays: 10,
    orderDeadline: "2027-02-04",
    iconType: "Heart",
  },
  {
    id: "VAL-004",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Lindt Swiss Luxury Selection Assorted Pralines - 145g Imported Gift Box",
    subCategory: "Chocolates & Confectionery",
    occasionTag: "VALENTINE",
    significanceTag: "Ultra-Premium Swiss Gifting",
    culturalSignificance:
      "Imported master-chocolatier creation commanding premium prices on quick-commerce for luxury gifting.",
    targetAudience: "Luxury Romantic Gifting",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.0,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 550,
    suggestedMSRP: 795,
    profitMarginPercent: 30.8,
    recommendedUnitsSmall: 40,
    recommendedUnitsMedium: 160,
    recommendedUnitsEnterprise: 900,
    procurementLeadDays: 14,
    orderDeadline: "2027-01-31",
    iconType: "Sparkles",
  },
  {
    id: "VAL-005",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Nestlé KitKat Dessert Delight Truffle Chocolate - (Pack of 3 Bars x 50g)",
    subCategory: "Chocolates & Confectionery",
    occasionTag: "VALENTINE",
    significanceTag: "Crispy Wafer Celebration Pack",
    culturalSignificance:
      "Beloved crispy wafer fingers with rich chocolate truffle coating; highly requested budget Valentine treat.",
    targetAudience: "Students & Quick-Commerce Shoppers",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.7,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 120,
    suggestedMSRP: 180,
    profitMarginPercent: 33.3,
    recommendedUnitsSmall: 120,
    recommendedUnitsMedium: 500,
    recommendedUnitsEnterprise: 3000,
    procurementLeadDays: 8,
    orderDeadline: "2027-02-06",
    iconType: "Package",
  },
  {
    id: "VAL-006",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Bisk Farm Royal Touch Belgian Chocolate Wafer Rolls - 300g Luxury Reusable Tin",
    subCategory: "Packaged Bakery & Cookies",
    occasionTag: "VALENTINE",
    significanceTag: "Crunchy Sweet Gifting",
    culturalSignificance:
      "Crispy wafer rolls filled with rich Belgian cocoa cream packaged in a romantic reusable metallic tin.",
    targetAudience: "Gift Basket Assemblers",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.5,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 160,
    suggestedMSRP: 245,
    profitMarginPercent: 34.7,
    recommendedUnitsSmall: 70,
    recommendedUnitsMedium: 280,
    recommendedUnitsEnterprise: 1500,
    procurementLeadDays: 10,
    orderDeadline: "2027-02-04",
    iconType: "Cake",
  },
  {
    id: "VAL-007",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Lotte Choco Pie Festive Marshmallow Snack Cakes - (Box of 12 Individual Packs)",
    subCategory: "Packaged Bakery & Cookies",
    occasionTag: "VALENTINE",
    significanceTag: "Cute Couple Sharing Treat",
    culturalSignificance:
      "Soft biscuit cakes filled with fluffy marshmallow cream; popular lighthearted Valentine snack box.",
    targetAudience: "Young Couples & Teen Gifting",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.3,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 110,
    suggestedMSRP: 160,
    profitMarginPercent: 31.3,
    recommendedUnitsSmall: 90,
    recommendedUnitsMedium: 360,
    recommendedUnitsEnterprise: 2000,
    procurementLeadDays: 8,
    orderDeadline: "2027-02-06",
    iconType: "Package",
  },
  {
    id: "VAL-008",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Paper Boat Sparkling Pomegranate & Cranberry Fruit Drink - (Pack of 6 x 250ml Cans)",
    subCategory: "Packaged Beverages",
    occasionTag: "VALENTINE",
    significanceTag: "Non-Alcoholic Toasting Sips",
    culturalSignificance:
      "Ruby-red sparkling fizzy fruit drink ordered for Valentine candlelit dinners and romantic celebrations.",
    targetAudience: "Valentine Dinner Hosts",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.4,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 180,
    suggestedMSRP: 270,
    profitMarginPercent: 33.3,
    recommendedUnitsSmall: 60,
    recommendedUnitsMedium: 240,
    recommendedUnitsEnterprise: 1400,
    procurementLeadDays: 8,
    orderDeadline: "2027-02-06",
    iconType: "Sparkles",
  },
  {
    id: "VAL-009",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Bikaji Kaju Barfi Heart-Shaped Sweet Box - 250g Vacuum Pack",
    subCategory: "Packaged Sweets & Mithai",
    occasionTag: "VALENTINE",
    significanceTag: "Fusion Indian Romance Mithai",
    culturalSignificance:
      "Traditional pure cashew barfi cut into romantic heart shapes for customers seeking traditional Indian gifting.",
    targetAudience: "Traditional Indian Romantic Gifting",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.6,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 210,
    suggestedMSRP: 310,
    profitMarginPercent: 32.3,
    recommendedUnitsSmall: 60,
    recommendedUnitsMedium: 250,
    recommendedUnitsEnterprise: 1400,
    procurementLeadDays: 8,
    orderDeadline: "2027-02-06",
    iconType: "Cake",
  },
  {
    id: "VAL-010",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "4700BC Gourmet Chocolate Caramel & Sea Salt Popcorn - 125g Designer Canister",
    subCategory: "Healthy Fasting Snacks",
    occasionTag: "VALENTINE",
    significanceTag: "Valentine Movie-Night Treat",
    culturalSignificance:
      "Designer popcorn canister coated in dark chocolate and caramel; perfect for cozy Valentine couple streaming nights.",
    targetAudience: "Movie Night Couples",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.8,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 120,
    suggestedMSRP: 185,
    profitMarginPercent: 35.1,
    recommendedUnitsSmall: 80,
    recommendedUnitsMedium: 320,
    recommendedUnitsEnterprise: 1800,
    procurementLeadDays: 6,
    orderDeadline: "2027-02-08",
    iconType: "Sparkles",
  },

  // --- MAHA SHIVRATRI FASTING & HOLY FOODS (7 FMCG Packed Food SKUs) ---
  {
    id: "SHIV-001",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Paper Boat Kesaria Thandai with Almonds & Fennel - (Pack of 6 x 250ml Cans)",
    subCategory: "Packaged Beverages",
    occasionTag: "SHIVRATRI",
    significanceTag: "Maha Shivratri Mandatory Thandai",
    culturalSignificance:
      "Spiced cooling milk beverage with crushed almonds, melon seeds, and fennel; Lord Shiva's most auspicious celebratory drink.",
    targetAudience: "All Devotees Observing Vigil",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.8,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 210,
    suggestedMSRP: 300,
    profitMarginPercent: 30.0,
    recommendedUnitsSmall: 120,
    recommendedUnitsMedium: 500,
    recommendedUnitsEnterprise: 3200,
    procurementLeadDays: 10,
    orderDeadline: "2027-02-24",
    iconType: "Coffee",
  },
  {
    id: "SHIV-002",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Farmley Himalayan Salt & Pepper Roasted Makhana (Fox Nuts) - 150g Airtight Jar",
    subCategory: "Healthy Fasting Snacks",
    occasionTag: "SHIVRATRI",
    significanceTag: "Shivratri Fasting Crunch",
    culturalSignificance:
      "Lightweight energy snack roasted with pure sendha namak; sustains devotees through 24-hour Shiva vigil without breaking fast.",
    targetAudience: "All Fasting Households",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.3,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 135,
    suggestedMSRP: 210,
    profitMarginPercent: 35.7,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 400,
    recommendedUnitsEnterprise: 2500,
    procurementLeadDays: 10,
    orderDeadline: "2027-02-24",
    iconType: "Leaf",
  },
  {
    id: "SHIV-003",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Haldiram's Phalahari Farali Chivda & Potato Mixture - 200g Pouch",
    subCategory: "Packaged Snacks & Namkeen",
    occasionTag: "SHIVRATRI",
    significanceTag: "Pure Vrat Snacking",
    culturalSignificance:
      "Certified gluten-free and satvik fasting namkeen made from shredded potatoes, peanuts, and rock salt.",
    targetAudience: "Fasting Devotees",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.1,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 55,
    suggestedMSRP: 85,
    profitMarginPercent: 35.3,
    recommendedUnitsSmall: 110,
    recommendedUnitsMedium: 450,
    recommendedUnitsEnterprise: 2600,
    procurementLeadDays: 8,
    orderDeadline: "2027-02-26",
    iconType: "Package",
  },
  {
    id: "SHIV-004",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Amul Kool Kesar Badam Flavored Milk - (Pack of 6 Cans x 200ml)",
    subCategory: "Packaged Beverages",
    occasionTag: "SHIVRATRI",
    significanceTag: "Night Vigil Energy Drink",
    culturalSignificance:
      "Ready-to-drink rich saffron and almond milk; ideal for night vigils at Shiva temples and breaking the fast.",
    targetAudience: "Temple Devotees & Youths",
    demandSurgeLevel: "HIGH",
    demandMultiplier: 3.7,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 175,
    suggestedMSRP: 240,
    profitMarginPercent: 27.1,
    recommendedUnitsSmall: 80,
    recommendedUnitsMedium: 320,
    recommendedUnitsEnterprise: 1800,
    procurementLeadDays: 8,
    orderDeadline: "2027-02-26",
    iconType: "Coffee",
  },
  {
    id: "SHIV-005",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Fortune Kuttu Atta (Buckwheat Fasting Flour) - 500g Vacuum Pack",
    subCategory: "Vrat & Fasting Staples",
    occasionTag: "SHIVRATRI",
    significanceTag: "Evening Vrat Dinner Puris",
    culturalSignificance:
      "Used to cook fasting puris and halwa on Maha Shivratri evening after completing the 4 prahar pujas.",
    targetAudience: "Fasting Devotee Households",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.2,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 68,
    suggestedMSRP: 105,
    profitMarginPercent: 35.2,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 400,
    recommendedUnitsEnterprise: 2400,
    procurementLeadDays: 10,
    orderDeadline: "2027-02-24",
    iconType: "Wheat",
  },
  {
    id: "SHIV-006",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Classic Sabudana Tapioca Pearls - 1kg Double Sealed Pouch",
    subCategory: "Vrat & Fasting Staples",
    occasionTag: "SHIVRATRI",
    significanceTag: "Sabudana Khichdi Offering",
    culturalSignificance:
      "Most popular meal for the morning and evening of Shivratri fast; provides quick and sustained carbohydrates.",
    targetAudience: "Fasting Families",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.0,
    complianceTag: "VEG_VRAT_CERTIFIED",
    wholesaleCost: 72,
    suggestedMSRP: 115,
    profitMarginPercent: 37.4,
    recommendedUnitsSmall: 120,
    recommendedUnitsMedium: 450,
    recommendedUnitsEnterprise: 2800,
    procurementLeadDays: 10,
    orderDeadline: "2027-02-24",
    iconType: "Package",
  },
  {
    id: "SHIV-007",
    festivalId: "FEST_2027_VALENTINES_SHIVRATRI",
    festivalName: "Valentine's & Maha Shivratri",
    productName: "Amul Pure Cow Desi Ghee - 1 Liter Sealed Tin",
    subCategory: "Pure Ghee & Dairy",
    occasionTag: "SHIVRATRI",
    significanceTag: "Shiva Abhishekam & Prasad Cooking",
    culturalSignificance:
      "Offered to Lord Shiva during Panchamrit Abhishekam and used for preparing divine temple prasad.",
    targetAudience: "Pooja Organizers & Households",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.9,
    complianceTag: "HOLY_RITUAL",
    wholesaleCost: 560,
    suggestedMSRP: 690,
    profitMarginPercent: 18.8,
    recommendedUnitsSmall: 50,
    recommendedUnitsMedium: 220,
    recommendedUnitsEnterprise: 1400,
    procurementLeadDays: 8,
    orderDeadline: "2027-02-26",
    iconType: "Coffee",
  },

  // =========================================================================
  // 10. HOLI & RAMADAN / EID 2027 (March 20 - 31) — Gujiya, Thandai & Iftar Dates
  // =========================================================================
  {
    id: "HOLI-001",
    festivalId: "FEST_2027_HOLI_EID",
    festivalName: "Holi & Ramadan / Eid ul-Fitr 2027",
    productName: "Haldiram's Baked Mawa Gujiya in Saffron Sugar Glaze - (500g Vacuum Gift Box)",
    subCategory: "Packaged Sweets & Mithai",
    significanceTag: "Holi's #1 Signature Mithai",
    culturalSignificance:
      "Crispy golden pastries stuffed with khoya and dry fruits. Holi is incomplete without offering Gujiya to visiting friends.",
    targetAudience: "All Holi Celebrants",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 5.0,
    complianceTag: "CONFECTIONERY",
    wholesaleCost: 260,
    suggestedMSRP: 395,
    profitMarginPercent: 34.2,
    recommendedUnitsSmall: 120,
    recommendedUnitsMedium: 550,
    recommendedUnitsEnterprise: 3500,
    procurementLeadDays: 12,
    orderDeadline: "2027-03-08",
    iconType: "Cake",
  },
  {
    id: "HOLI-002",
    festivalId: "FEST_2027_HOLI_EID",
    festivalName: "Holi & Ramadan / Eid ul-Fitr 2027",
    productName: "Paper Boat Royal Kesaria Thandai Drink Syrup - 750ml Glass Bottle",
    subCategory: "Packaged Beverages",
    significanceTag: "Instant Holi Welcome Drink",
    culturalSignificance:
      "Concentrated saffron and dry fruit syrup. Just add chilled milk to serve traditional Holi Thandai in seconds.",
    targetAudience: "Holi Party Hosts",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.8,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 190,
    suggestedMSRP: 285,
    profitMarginPercent: 33.3,
    recommendedUnitsSmall: 100,
    recommendedUnitsMedium: 450,
    recommendedUnitsEnterprise: 2800,
    procurementLeadDays: 10,
    orderDeadline: "2027-03-10",
    iconType: "Coffee",
  },
  {
    id: "HOLI-003",
    festivalId: "FEST_2027_HOLI_EID",
    festivalName: "Holi & Ramadan / Eid ul-Fitr 2027",
    productName: "Haldiram's Crispy Mathri & Namakpara Snacks - 400g Festive Pouch",
    subCategory: "Packaged Snacks & Namkeen",
    significanceTag: "Holi Savory Counterpart",
    culturalSignificance:
      "Crispy savory bites served alongside sweet Gujiya to balance the festive palate.",
    targetAudience: "Holi Hosts & Families",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 3.9,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 85,
    suggestedMSRP: 130,
    profitMarginPercent: 34.6,
    recommendedUnitsSmall: 90,
    recommendedUnitsMedium: 360,
    recommendedUnitsEnterprise: 2200,
    procurementLeadDays: 8,
    orderDeadline: "2027-03-12",
    iconType: "Package",
  },
  {
    id: "EID-001",
    festivalId: "FEST_2027_HOLI_EID",
    festivalName: "Holi & Ramadan / Eid ul-Fitr 2027",
    productName: "Premium Saudi Medjool Dates (Jumbo Soft & Sweet) - 1kg Luxury Gift Box",
    subCategory: "Dry Fruits & Nuts Hampers",
    significanceTag: "Ramadan Fast-Breaking Essential",
    culturalSignificance:
      "According to Islamic Sunnah, Muslims break their daily Roza fast at sunset with pure natural dates.",
    targetAudience: "Fasting Muslim Households",
    demandSurgeLevel: "EXTREME",
    demandMultiplier: 4.7,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 550,
    suggestedMSRP: 850,
    profitMarginPercent: 35.3,
    recommendedUnitsSmall: 80,
    recommendedUnitsMedium: 350,
    recommendedUnitsEnterprise: 2200,
    procurementLeadDays: 15,
    orderDeadline: "2027-03-05",
    iconType: "Gift",
  },
  {
    id: "EID-002",
    festivalId: "FEST_2027_HOLI_EID",
    festivalName: "Holi & Ramadan / Eid ul-Fitr 2027",
    productName: "Bambino Roasted Fine Laccha Vermicelli (Seviyan) - 500g Sealed Pack",
    subCategory: "Vrat & Fasting Staples",
    significanceTag: "Eid Sheer Khurma Staple",
    culturalSignificance:
      "The mandatory ingredient for preparing Sheer Khurma on Eid ul-Fitr morning to celebrate after 30 days of Ramadan.",
    targetAudience: "Eid Celebrants",
    demandSurgeLevel: "VERY_HIGH",
    demandMultiplier: 4.4,
    complianceTag: "PACKED_FOOD_FMCG",
    wholesaleCost: 55,
    suggestedMSRP: 85,
    profitMarginPercent: 35.3,
    recommendedUnitsSmall: 110,
    recommendedUnitsMedium: 450,
    recommendedUnitsEnterprise: 2600,
    procurementLeadDays: 10,
    orderDeadline: "2027-03-10",
    iconType: "Wheat",
  },
];
